Update supported-versions-auto-update.yml

diff --git a/.github/workflows/supported-versions-auto-update.yml b/.github/workflows/supported-versions-auto-update.yml
--- a/.github/workflows/supported-versions-auto-update.yml
+++ b/.github/workflows/supported-versions-auto-update.yml
@@ -161,16 +161,21 @@ jobs:
 
             ISSUE_URL=$(cat issue_url.txt)
             if [[ -z "${ISSUE_URL}" ]]; then
-              echo "::error::Unable to retrieve the issue url !"
+              echo "::error::Unable to retrieve the issue URL !"
               exit 1
             fi
-
+            ISSUE_ID=$(gh issue view "${ISSUE_URL}" --json number --jq '.number')
+            if [[ -z "${ISSUE_ID}" ]]; then
+              echo "::error::Unable to retrieve the issue ID !"
+              exit 1
+            fi
+            
             echo "Update issue with proper link to create the PR"
             PR_ENCODED_TITLE=$(jq -rn --arg x "${ISSUE_TITLE}" '$x|@uri')
-            PR_BODY_ENCODED=$(jq -rn --arg x "${BODY_FILE}" '$x|@uri')
+            PR_BODY_ENCODED=$(jq -rn --arg x "Fix #${ISSUE_ID}" '$x|@uri')
             echo "${ISSUE_BODY_HEADER}" > ${BODY_FILE}
             echo "" >> ${BODY_FILE}
-            echo "Create PR [there](https://github.com/${REPO_NAME}/compare/${BRANCH}?quick_pull=1&assignees=${ASSIGNEE_HANDLES}&title=${PR_ENCODED_TITLE}&body=${PR_BODY_ENCODED}" >> ${BODY_FILE}
+            echo "Create PR [there](https://github.com/${REPO_NAME}/compare/${BRANCH}?quick_pull=1&assignees=${ASSIGNEE_HANDLES}&title=${PR_ENCODED_TITLE}&body=${PR_BODY_ENCODED})" >> ${BODY_FILE}
 
             gh issue edit "${ISSUE_URL}" --body-file "${BODY_FILE}"
           else
